apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-set
spec:
  replicas: 1
  serviceName: "prometheus"
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: 500M
            limits:
              memory: 500M
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-pvc
              mountPath: /prometheus/
      initContainers:
        - name: prometheus-data-permission-fix
          image: busybox
          command: [ "/bin/chmod","-R","777", "/prometheus" ]
          volumeMounts:
            - name: prometheus-pvc
              mountPath: /prometheus

      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  volumeClaimTemplates:
    - metadata:
        name: prometheus-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: do-block-storage
